"""empty message

Revision ID: 257708b3841d
Revises: 753d3e3b217f
Create Date: 2023-01-03 18:47:21.718104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257708b3841d'
down_revision = '753d3e3b217f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', sa.String(), nullable=False))
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('customer', sa.Column('postal_code', sa.String(), nullable=False))
    op.add_column('customer', sa.Column('register_at', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'videos_checked_out_count')
    op.drop_column('customer', 'register_at')
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###
