"""empty message

Revision ID: 68ec35ff3d8f
Revises: 778116edb50f
Create Date: 2023-01-07 20:46:47.517661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ec35ff3d8f'
down_revision = '778116edb50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'available_inventory',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
