"""empty message

Revision ID: 7757eaa2b620
Revises: eb90065ba728
Create Date: 2023-01-03 16:23:05.973641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7757eaa2b620'
down_revision = 'eb90065ba728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'register_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'register_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
