"""empty message

Revision ID: 880d69725e6e
Revises: 257708b3841d
Create Date: 2023-01-03 18:48:09.730203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880d69725e6e'
down_revision = '257708b3841d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'register_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('register_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
