"""empty message

Revision ID: e3185f3235db
Revises: 880d69725e6e
Create Date: 2023-01-03 18:49:40.975153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3185f3235db'
down_revision = '880d69725e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('registerd_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'registerd_at')
    # ### end Alembic commands ###
